apiVersion: v1
kind: ConfigMap
metadata:
  name: instance-aws-config
data:
  hostname: "provisioner-test-001.oczadly.io"
  awsRegion: "eu-central-1"
  awsAccountId: "123456789012"
  ServiceAccountRoleArn: "arn:aws:iam::123456789012:role/provisioner-test-001-irsa"
  objectStorageBucket: "provisioner-test-001-builds"
  usermanagedDbHostname: "provisioner-test-001.cluster-xxx.eu-central-1.rds.amazonaws.com"
  workloadName: "provisioner-test-001"
  mcpServerRoleArn: "arn:aws:iam::123456789012:role/provisioner-test-001-mcp"
