apiVersion: v1
kind: Namespace
metadata:
  name: provisioner-test-001
  labels:
    infra.oczadly.io/workload-type: backend-app
    infra.oczadly.io/tenant: provisioner-test-001
    infra.oczadly.io/instance-tier: dev
