apiVersion: v1
kind: Namespace
metadata:
  name: provisioner-test
  labels:
    infra.oczadly.io/workload-type: backend-app
    infra.oczadly.io/tenant: provisioner-test
    infra.oczadly.io/instance-tier: trials
